name: Build and Push to ACR

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    uses: HammadTariq14/devops-template/.github/workflows/build-and-push.yaml@main
    with:
      image_name: hello-world-api
      acr_name: ampliordevacr
      environment: dev
    secrets: inherit
